import { ImageResponse } from 'next/og';
import { getCourseForMetadata } from './api/server';

/**
 * Shared renderer for the Open Graph / Twitter card images generated by the
 * `opengraph-image` and `twitter-image` file conventions. Satori only supports a
 * flexbox subset of CSS, so everything here is inline styles on flex containers.
 */
export const OG_SIZE = { width: 1200, height: 630 };
export const OG_CONTENT_TYPE = 'image/png';

const DEEP = '#26215C';
const PRIMARY = '#7F77DD';
const LILAC = '#EEEDFE';

export function renderOgImage({
  eyebrow,
  title,
  subtitle,
}: {
  eyebrow?: string;
  title: string;
  subtitle?: string;
}) {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          padding: '72px',
          background: `linear-gradient(135deg, ${DEEP} 0%, #3C3489 55%, ${PRIMARY} 100%)`,
          color: '#FFFFFF',
          fontFamily: 'sans-serif',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              width: '56px',
              height: '56px',
              borderRadius: '16px',
              background: LILAC,
              color: DEEP,
              fontSize: '34px',
              fontWeight: 700,
            }}
          >
            H
          </div>
          <div style={{ fontSize: '30px', fontWeight: 600, letterSpacing: '-0.5px' }}>Hamplard</div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {eyebrow ? (
            <div
              style={{
                display: 'flex',
                alignSelf: 'flex-start',
                padding: '8px 18px',
                borderRadius: '999px',
                background: 'rgba(238, 237, 254, 0.18)',
                color: LILAC,
                fontSize: '24px',
                fontWeight: 600,
                textTransform: 'uppercase',
                letterSpacing: '1.5px',
              }}
            >
              {eyebrow}
            </div>
          ) : null}
          <div
            style={{
              display: 'flex',
              fontSize: title.length > 60 ? '56px' : '68px',
              fontWeight: 700,
              lineHeight: 1.15,
              letterSpacing: '-1.5px',
            }}
          >
            {title}
          </div>
          {subtitle ? (
            <div style={{ display: 'flex', fontSize: '30px', color: LILAC, lineHeight: 1.35 }}>
              {subtitle}
            </div>
          ) : null}
        </div>

        <div style={{ display: 'flex', fontSize: '26px', color: LILAC }}>
          Africa&apos;s online vocational skills platform
        </div>
      </div>
    ),
    { ...OG_SIZE },
  );
}

/** Trims to a whole word so long course titles do not blow out the card. */
function truncate(value: string, max: number): string {
  if (value.length <= max) return value;
  const clipped = value.slice(0, max);
  const lastSpace = clipped.lastIndexOf(' ');
  return `${(lastSpace > max * 0.6 ? clipped.slice(0, lastSpace) : clipped).trimEnd()}…`;
}

// The cards themselves live here so that opengraph-image and twitter-image can each
// declare their own `runtime`/`alt`/`size` exports. Re-exporting those from a sibling
// route file does not work — Next only picks up statically declared route config.

export const SITE_OG_ALT = 'Hamplard — learn practical vocational skills online';
export const COURSE_OG_ALT = 'Course on Hamplard';

export function renderSiteOgImage() {
  return renderOgImage({
    title: 'Learn practical skills that pay',
    subtitle: 'Tailoring, makeup, baking, photography and more.',
  });
}

export async function renderCourseOgImage(id: string) {
  const course = await getCourseForMetadata(id);

  if (!course) {
    return renderOgImage({
      eyebrow: 'Course',
      title: 'Learn practical skills that pay',
      subtitle: 'Tailoring, makeup, baking, photography and more.',
    });
  }

  const instructor = course.instructor?.name?.trim();
  const lessons = course.totalLessons ?? 0;
  const subtitle = [
    instructor ? `By ${instructor}` : null,
    lessons > 0 ? `${lessons} lesson${lessons === 1 ? '' : 's'}` : null,
    course.level ? course.level.charAt(0).toUpperCase() + course.level.slice(1) : null,
  ]
    .filter(Boolean)
    .join(' · ');

  return renderOgImage({
    eyebrow: course.category || 'Course',
    title: truncate(course.title, 80),
    subtitle,
  });
}
